# Generated by Django 4.1.7 on 2023-04-04 08:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loginapp', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='shop_id',
            new_name='lab_id',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='shop_name',
            new_name='lab_name',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('lab_id', 'user')},
        ),
    ]
