# Generated by Django 4.1.7 on 2023-04-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_templateselect'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateselect',
            name='room',
            field=models.CharField(default=99, max_length=100),
            preserve_default=False,
        ),
    ]
