# Generated by Django 4.1.7 on 2023-04-05 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_rename_shop_id_review_lab_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
